# Set to true to add assignees to PRs
addAssignees: true

# A list of assignees, overrides reviewers if set
assignees:
  - peterus

# A number of assignees to add to the PRs
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
numberOfAssignees: 0
