name: PlatformIO CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  precompile:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install python3-setuptools python3-wheel
      - run: export PATH="~/.local/bin:$PATH"
      - run: pip3 -v install platformio
      - run: which platformio
      - uses: actions/checkout@v2
      - run: pio run
    
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: check for updates
      run: platformio update
    - name: run cppcheck
      run: echo platformio check --fail-on-defect low --fail-on-defect medium --fail-on-defect high
    - name: compile
      run: platformio run
