name: PlatformIO CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: check for updates
      run: platformio update
    - name: run cppcheck
      run: platformio check --fail-on-defect low --fail-on-defect medium --fail-on-defect high
    - name: compile
      run: platformio run
