name: PlatformIO CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  PlatformIO-Check:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install python3-setuptools python3-wheel
      - run: pip3 install platformio
      - run: echo "::add-path::~/.local/bin"
      - uses: actions/checkout@v2
      - run: platformio check --fail-on-defect low --fail-on-defect medium --fail-on-defect high

  PlatformIO-Build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install python3-setuptools python3-wheel
      - run: pip3 install platformio
      - run: echo "::add-path::~/.local/bin"
      - uses: actions/checkout@v2
      - run: platformio run
      - uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: .pio/build/*/firmware.bin
